# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

desc "Create the app-debug apk"
  lane :beta do
    gradle(
      task: 'assemble',
      build_type: 'debug'
    )
  end

# https://github.com/microsoft/fastlane-plugin-appcenter
desc "Upload to App Center"
  lane :upload_to_app_center do
  appcenter_upload(
  api_token: ENV["FASTLANE_TOKEN"],
  owner_name: "jprendy",
  app_name: "Android-App",
  file: "app/build/outputs/apk/debug/app-debug.apk",
  notify_testers: false,
  release_notes: "Uploading app to App Center"
  )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
