name: CI pull request

on:
  push: 
    branches:
      - master
      - develop
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    #  runs-on: ubuntu-latest # need to use linux if we want to use the linter
    runs-on: macos-11
    environment: 
      name: Deployment
      url: https://appcenter.ms/

    steps:
    - uses: actions/checkout@v2.3.4
    
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    # Run Linter against code base, see https://github.com/github/super-linter for how the linter works
    - name: Install Dependencies
      run: bundle install

    - name: Create Debug APK
      run: bundle exec fastlane beta

    - name: Create jacocoTestReport
      uses: ReactiveCircus/android-emulator-runner@v2.19.0
      with:
        api-level: 28
        script: ./gradlew jacocoTestReport

    - name: Upload to App Center
      env:
        FASTLANE_TOKEN : ${{ secrets.FASTLANE_TOKEN }}
      run: bundle exec fastlane upload_to_app_center

    - name: Upload Fastlane Test results
      uses: actions/upload-artifact@v1
      with:
        name: Fastlane Test Results
        path: app/build/reports/jacoco
