name: CI pull request

on:
  push: 
    branches:
      - master
      - develop
    paths-ignore:
      - 'README.md'
      - '.github/**'
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: macos-10.15
  #  runs-on: ubuntu-latest # need to use linux if we want to use the linter

    steps:
    - uses: actions/checkout@v2

    # Run Linter against code base, see https://github.com/github/super-linter for how the linter works
    - name: Install Dependencies
      run: bundle install

    - name: Create Debug APK
      run: bundle exec fastlane beta

    - name: Upload to App Center
      env:
        FASTLANE_TOKEN : ${{ secrets.FASTLANE_TOKEN }}
      run: bundle exec fastlane upload_to_app_center

    # Artifacts allow you to persist data like test results after a job has completed, see https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts for how the artifacts works
    # - name: Upload Fastlane Test results
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: Fastlane Test Results
    #     path: fastlane/test_output    

